### ISSUE TITLE
No way to attach PxSimulationEventCallback  / PxSimulationEventCallback  

### ISSUE THREAD

**Issue by aguerrieri82** [Cysharp/MagicPhysX#18]
There is any way to implement `PxSimulationEventCallback` / `PxSimulationEventCallback` interfaces in c# to receive events / callbaks ?

I understand is not an easy task, I tried myself to rebuild the v-tables for `PxContactModifyCallback` / `PxSimulationEventCallback` interfaces without success (nothing is called back, no exceptions).

This what i've done so far:

```c#
[UnmanagedFunctionPointer(CallingConvention.ThisCall)]
delegate void OnContactModifyDelegate(PxContactModifyPair* pairs, uint count);

_handler = (PxContactModifyCallback*)Marshal.AllocHGlobal(sizeof(PxSimulationEventCallback));

_handler->vtable_ = (void*)Marshal.AllocHGlobal(4 * sizeof(nint));
//first qword is 0, second is a pointer to the typeinfo, following the virtual functions. 
//No idea how to recover typeinfo descriptor pointer
((nint*)_handler->vtable_)[2] = Marshal.GetFunctionPointerForDelegate((OnContactModifyDelegate)OnContactModify);
((nint*)_handler->vtable_)[3] = Marshal.GetFunctionPointerForDelegate((VoidDelegate)Distructor);
```

**Comment by MartinPrograms** [comment]
I've been having the same issue, found out that the function PxSimulationFilterShader must also be set. However a variable sent to that function seems to be incorrectly set.

```cs
[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
delegate PxFilterFlags PxSimulationFilterShader(uint attributes0, PxFilterData filterData0, uint attributes1, PxFilterData filterData1, ref PxPairFlags pairFlags, IntPtr constantBlock, uint constantBlockSize);
    
static PxFilterFlags CustomFilterShader(uint attributes0, PxFilterData filterData0, uint attributes1, PxFilterData filterData1, ref PxPairFlags pairFlags, IntPtr constantBlock, uint constantBlockSize)
{
    return PxFilterFlags.Kill;
}
```

How the original physx version works is that you decide based on the attributes and filterdata what the PxPairFlags should be, in this case however pairFlags is a broken memory address.

Unfortunately we *have* to use a custom filter shader to properly assign the pairflags which if properly set calls the simulation event callback.

I have been at it for a while now, and still haven't been able to figure it out.

This is where I got the filter idea from
[NVIDIA Filter](https://docs.nvidia.com/gameworks/content/gameworkslibrary/physx/apireference/files/group__physics.html#g9db06e901a760fb02c06f27bf3e474b3)

[NVIDIA Sim callback](https://docs.nvidia.com/gameworks/content/gameworkslibrary/physx/apireference/files/classPxSimulationFilterCallback.html)
> You can enable the use of this contact modification callback by raising the flag [PxPairFlag::eMODIFY_CONTACTS](https://docs.nvidia.com/gameworks/content/gameworkslibrary/physx/apireference/files/structPxPairFlag.html#60e71a2948b030140f840766a3f7ac2f2465a37a9b236f662bda8d6636eed59b) in the filter shader/callback (see [PxSimulationFilterShader](https://docs.nvidia.com/gameworks/content/gameworkslibrary/physx/apireference/files/group__physics.html#g9db06e901a760fb02c06f27bf3e474b3)) for a pair of rigid body objects.

**Comment by MartinPrograms** [comment]
Potential solution?
https://github.com/EmbarkStudios/physx-rs/issues/145

Would have to make this in rust however, change the default there which would be sub optimal.

**Comment by MartinPrograms** [comment]
Found it. I have On Contact working.

(small code dump about what I did)
Creating the callbacks:

```cs
    var simcallback = new SimulationEventCallbackInfo();
        simcallback.collision_callback = (delegate* unmanaged[Cdecl]<void*, PxContactPairHeader*, PxContactPair*, uint, void>)Marshal.GetFunctionPointerForDelegate<CollisionCallback>(OnContactDelegateInstance).ToPointer();
        var callbackinfoithink = create_simulation_event_callbacks(&simcallback);
        sceneDesc.simulationEventCallback = callbackinfoithink;
        
        var thing = (delegate* unmanaged[Cdecl]<FilterShaderCallbackInfo*, PxFilterFlags>)Marshal.GetFunctionPointerForDelegate<CustomFilterShaderDelegate>(CustomFilterShaderInstance).ToPointer();
        enable_custom_filter_shader(&sceneDesc, thing, (uint)1);

```

And the actual callbacks:

```cs
[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void CustomFilterShaderDelegate(FilterShaderCallbackInfo* callbackInfo, PxFilterFlags filterFlags);
    
    static void CustomFilterShader(FilterShaderCallbackInfo* callbackInfo, PxFilterFlags filterFlags)
    {
        PxPairFlags flags = PxPairFlags.ContactDefault | PxPairFlags.NotifyTouchFound;
        
        callbackInfo->pairFlags[0] = flags;
    }
    
    public CustomFilterShaderDelegate CustomFilterShaderInstance = CustomFilterShader; // Assign the managed delegate to the unmanaged delegate instance
    
    
    
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    // public delegate*unmanaged[Cdecl]<void*, PxContactPairHeader*, PxContactPair*, uint, void> OnContactDelegate;
    public delegate void CollisionCallback(IntPtr userData, PxContactPairHeader pairHeader, PxContactPair contacts, uint flags);    

    static void OnContact(IntPtr userData, PxContactPairHeader pairHeader, PxContactPair contacts, uint flags)
    {
        // On Contact...
        // This took 7~ hours to get working.
Console.WriteLine("OnContact");
    }
    
    public CollisionCallback OnContactDelegateInstance = OnContact; // Assign the managed delegate to the unmanaged delegate instance
```
