### ISSUE TITLE
Support for Avalonia WEB/Mobile

### ISSUE THREAD

**Issue by RayanFarhat** [Cysharp/MagicPhysX#7]
To begin with, I want to express my gratitude for the effort you've dedicated to this project. I've been in search of a cross-platform engine like this for quite some time.

I am currently utilizing Avalonia in my application, which now boasts support for WebAssembly, Android, and iOS. I'm curious whether this project seamlessly functions on these platforms without requiring additional configurations. Have you had the opportunity to conduct any testing on this matter? Are you planning to keep supporting it in the future ?

Thank you.

**Comment by neuecc** [comment]
Thank you for your interest.
First, a native build is required, and currently, this project does not offer builds for iOS and Android.
https://github.com/Cysharp/MagicPhysX/blob/main/.github/workflows/build-physx.yml
However, physx-rs does allow for iOS and Android builds, and I have tried it locally.
If there is a contribution to add CI, it is possible to include it in the release package.

**Comment by RayanFarhat** [comment]
oh, okay thanks mate
